---
- name: Setup a firewall on CentOS
  ansible.builtin.package:
    name: firewalld
    state: present
  when: ansible_os_family == 'RedHat'

- name: Enable and start firewalld service
  ansible.builtin.systemd:
    name: firewalld
    enabled: yes
    state: started
  when: ansible_os_family == 'RedHat'

- name: Open firewall ports for SSH, HTTP, and HTTPS
  ansible.builtin.firewalld:
    port: "{{ item }}/tcp"
    permanent: yes
    state: enabled
  with_items:
    - 22
    - 80
    - 443
  when: ansible_os_family == 'RedHat'
